// Generated by CoffeeScript 1.7.1
(function() {
  var area, data, h, line, num, svg, temp, w, x, y, _i;

  data = [];

  for (num = _i = 1; _i <= 300; num = ++_i) {
    temp = [num, Math.random() * 30];
    data.push(temp);
  }

  w = 1000;

  h = 80;

  svg = d3.select('body').append('svg').attr('width', w).attr('height', h);

  x = d3.scale.linear().range([0, w]).domain(d3.extent(data, function(d) {
    return d[0];
  }));

  y = d3.scale.linear().range([20, h]).domain(d3.extent(data, function(d) {
    return d[1];
  }));

  line = d3.svg.line().x(function(d) {
    return x(d[0]);
  }).y(function(d) {
    return h - y(d[1]);
  });

  area = d3.svg.area().x(function(d) {
    return x(d[0]);
  }).y0(h).y1(function(d) {
    return h - y(d[1]);
  });

  svg.append('path').attr('class', 'line').attr('d', line(data));

  svg.append('path').attr('class', 'area').attr('d', area(data));

}).call(this);
