// Generated by CoffeeScript 1.7.1
(function() {
  var circles, color, dataset, edges, force, h, svg, w;

  dataset = {
    nodes: [
      {
        name: "Adam"
      }, {
        name: "Bob"
      }, {
        name: "Carrie"
      }, {
        name: "Donovan"
      }, {
        name: "Edward"
      }, {
        name: "Felicity"
      }, {
        name: "George"
      }, {
        name: "Hannah"
      }, {
        name: "Iris"
      }, {
        name: "Jerry"
      }
    ],
    edges: [
      {
        source: 0,
        target: 1
      }, {
        source: 0,
        target: 2
      }, {
        source: 0,
        target: 3
      }, {
        source: 0,
        target: 4
      }, {
        source: 1,
        target: 5
      }, {
        source: 2,
        target: 5
      }, {
        source: 2,
        target: 5
      }, {
        source: 3,
        target: 4
      }, {
        source: 5,
        target: 8
      }, {
        source: 5,
        target: 9
      }, {
        source: 6,
        target: 7
      }, {
        source: 7,
        target: 8
      }, {
        source: 8,
        target: 9
      }
    ]
  };

  w = 600;

  h = 400;

  color = d3.scale.category10();

  force = d3.layout.force().nodes(dataset.nodes).links(dataset.edges).size([w, h]).linkDistance([200]).charge([-100]).start();

  console.log(dataset);

  svg = d3.select('body').append('svg').attr('width', w).attr('height', h);

  edges = svg.selectAll('line').data(dataset.edges).enter().append('line').attr('stroke', '#ccc').attr('stroke-width', 1);

  circles = svg.selectAll('circle').data(dataset.nodes).enter().append('circle').attr('r', 10).attr('fill', function(d, i) {
    return color(i);
  }).call(force.drag);

  force.on('tick', function() {
    edges.attr('x1', function(d) {
      return d.source.x;
    }).attr('y1', function(d) {
      return d.source.y;
    }).attr('x2', function(d) {
      return d.target.x;
    }).attr('y2', function(d) {
      return d.target.y;
    });
    return circles.attr('cx', function(d) {
      return d.x;
    }).attr('cy', function(d) {
      return d.y;
    });
  });

}).call(this);
