// Generated by CoffeeScript 1.7.1
(function() {
  var color, dataset, groups, h, stack, svg, w, x, y, yMax;

  dataset = [
    [
      {
        x: 0,
        y: 5
      }, {
        x: 1,
        y: 4
      }, {
        x: 2,
        y: 2
      }, {
        x: 3,
        y: 7
      }, {
        x: 4,
        y: 23
      }
    ], [
      {
        x: 0,
        y: 10
      }, {
        x: 1,
        y: 12
      }, {
        x: 2,
        y: 19
      }, {
        x: 3,
        y: 23
      }, {
        x: 4,
        y: 17
      }
    ], [
      {
        x: 0,
        y: 22
      }, {
        x: 1,
        y: 28
      }, {
        x: 2,
        y: 32
      }, {
        x: 3,
        y: 35
      }, {
        x: 4,
        y: 43
      }
    ]
  ];

  stack = d3.layout.stack();

  stack(dataset);

  w = 600;

  h = 400;

  color = d3.scale.category10();

  yMax = d3.max(dataset, function(arr) {
    return d3.max(arr, function(item) {
      return item.y + item.y0;
    });
  });

  x = d3.scale.ordinal().domain(d3.range(dataset[0].length)).rangeRoundBands([0, w], 0.1);

  y = d3.scale.linear().domain([0, yMax]).range([0, h]);

  svg = d3.select('body').append('svg').attr('w', w).attr('h', h);

  groups = svg.selectAll('g').data(dataset).enter().append('g').attr('fill', function(d, i) {
    return color(i);
  });

  groups.selectAll('rect').data(function(d) {
    return d;
  }).enter().append('rect').attr({
    'x': function(d, i) {
      return x(i);
    },
    'y': function(d) {
      return h - y(d.y + d.y0);
    },
    'width': x.rangeBand(),
    'height': function(d) {
      return y(d.y);
    }
  });

}).call(this);
